import getpass
import logging
import tempfile
from pathlib import Path

from fit_tool import FitFile, FitFileBuilder
from fit_tool.data_message import DataMessage
from fit_tool.profile.messages.session_message import SessionMessage
from fit_tool.profile.profile_type import SubSport
from garminconnect import Garmin

TRAINERDAY_DIR = Path("~/Library/CloudStorage/Dropbox/Apps/TrainerDay").expanduser()
TOKENSTORE = Path("~/.garminconnect").expanduser()

log = logging.getLogger("main")


def setup_logging() -> None:
    logging.basicConfig(
        level=logging.INFO,
        format="[%(asctime)s %(levelname)-7s] %(message)s",
        datefmt="%Y-%m-%d %H:%M:%S",
    )


def login_to_garmin() -> Garmin:
    """
    Return an authenticated Garmin client, logging in at the start of a run.
    Reuses the cached session at TOKENSTORE when present and still valid
    (refreshing a near-expiry token); otherwise prompts for credentials (+ MFA)
    and caches a fresh session.
    """
    if TOKENSTORE.exists():
        try:
            client = Garmin()
            client.login(str(TOKENSTORE))  # validates + refreshes if near expiry
            log.info(f"Found cached Garmin session: {TOKENSTORE}.")
            return client
        except Exception as exc:
            log.warning(f"Cached session unusable: ({exc}); logging in fresh.")

    email = input("Garmin Connect email: ").strip()
    password = getpass.getpass("Garmin Connect password: ")
    client = Garmin(
        email=email,
        password=password,
        prompt_mfa=lambda: input("MFA/2FA code: ").strip(),
    )
    client.login(str(TOKENSTORE))  # caches tokens to TOKENSTORE
    log.info(f"Successfully logged in. Garmin session cached: {TOKENSTORE}")
    return client


def get_latest_fit_file(directory: Path) -> Path:
    """Return the most recently modified .fit file in the given directory."""
    files = [p for p in directory.glob("*.fit") if p.is_file()]
    if not files:
        raise FileNotFoundError(f"No .fit files found in: {directory}")
    latest = max(files, key=lambda p: p.stat().st_mtime)
    log.info(f"Found .fit file: {latest.resolve()}")
    return latest


def prepare_fit_file(fit_file: Path, activity_name: str) -> Path:
    """Return a temp copy of the FIT that Garmin will file as Virtual Cycling under
    activity_name, so nothing has to be fixed up over the API after upload.
    """
    log.info("Preparing .fit file for Garmin upload...")
    fit = FitFile.from_file(str(fit_file))

    builder = FitFileBuilder(auto_define=True)
    sessions = 0
    for record in fit.records:
        message = record.message
        if not isinstance(message, DataMessage):
            continue  # definitions are regenerated by the builder
        if isinstance(message, SessionMessage):
            # Rebuilt rather than edited: the decoded session has no slot for
            # sport_profile_name, a field TrainerDay never wrote.
            rebuilt = SessionMessage()
            rebuilt.local_id = message.local_id
            for field in message.fields:
                if field.get_value() is not None:
                    rebuilt.get_field(field.field_id).set_value(0, field.get_value())
            rebuilt.sub_sport = SubSport.VIRTUAL_ACTIVITY
            rebuilt.sport_profile_name = activity_name
            message = rebuilt
            sessions += 1
        builder.add(message)

    if not sessions:
        raise ValueError(f"No session message found in: {fit_file.name}")

    patched_file = Path(tempfile.mkstemp(suffix=".fit")[1])
    builder.build().to_file(str(patched_file))
    log.info(f"Prepared .fit file as virtual_activity, named {activity_name!r}.")
    return patched_file


def main() -> None:
    setup_logging()

    garmin_client = login_to_garmin()
    fit_file = get_latest_fit_file(directory=TRAINERDAY_DIR)
    patched_fit_file = prepare_fit_file(fit_file=fit_file, activity_name=fit_file.stem)
    result = garmin_client.import_activity(str(patched_fit_file))
    log.info(f"Garmin upload initiated. Result: {result}")


if __name__ == "__main__":
    main()
